### ISSUE TITLE
Please add typings

### ISSUE THREAD

**Issue by arminrosu** [derhuerst/db-stations-autocomplete#12]
An `index.d.ts` with:

```ts
export interface Station {
  id: string;
  relevance: number;
  score: number;
  weight: number;
}

function autocomplete(query: string, results?: number, fuzzy?: boolean, completion?: boolean): Station[];

export default autocomplete;
```

Might be enough.

Thanks :)

**Comment by derhuerst** [comment]
Although I'd like to support typing-based dev workflows with my libs, I would like to avoid another item on the maintenance list that I don't directly benefit from, as I wouldn't use them by myself.

Given that I write untyped/plain JS, a disconnect between the typings and the actual code might easily happen *anyways*, so have you considered adding the typings to the [DefinitelyTyped collection](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by arminrosu** [comment]
@derhuerst I highly recommend using Typescript, it's adds a lot of goodness to the dev process. I'd rather not add it to the Definitely Typed collection, then I'd have to maintain code I'm not going to be using for long. 

I think we can close this issue then. Rock on 🤘

**Comment by derhuerst** [comment]
I haven't used TypeScript a lot so far, but from my subjective judgement, the moments where it would have been worth its costs are very rare.
